### ISSUE TITLE
wish: highlight current window

### ISSUE THREAD

**Issue by markstos** [edzdez/sway-easyfocus#11]
It would be a nice enhancement if the currently focused window was visually noted during the overlay.

For example, usually white letters are shown on a black square. Perhaps for the currently focused window, black letters on a white square could be used.

**Comment by markstos** [comment]
I believe this is the right code to a new CSS class to the focused window. However, I'm not having any luck targeting the CSS class to get it to display differently:

```diff
diff --git a/src/ui.rs b/src/ui.rs
index 771d94e..d15948e 100644
--- a/src/ui.rs
+++ b/src/ui.rs
@@ -80,6 +80,11 @@ fn build_ui(app: &Application, args: Arc<Args>, conn: Arc<Mutex<Connection>>) {
         // TODO: make this work for workspaces with more than 26 windows
         label.set_markup(&format!("{}", ('a' as usize + idx % 26) as u8 as char));
         fixed.put(&label, x, y);
+
+        // Apply a CSS class to the focused window so it can be stylced differently
+        if window.focused {
+            fixed.set_widget_name("focused");
+        }
     }
 
     window.add(&fixed);
```

**Comment by edzdez** [comment]
Thanks @markstos! You were very close; after taking a quick look at the gtkrs docs, I tried  `widget.style_context().add_class(class);`, which seems to have worked.
