### ISSUE TITLE
wish: more ergonomic default keys (start with home row keys)

### ISSUE THREAD

**Issue by markstos** [edzdez/sway-easyfocus#15]
Other tools which work in a similar way often have a nice touch by putting the easiest to reach keys as the most likely ones to be used for labels.  Here's how `wmfocus` does it:

https://github.com/svenstaro/wmfocus/blob/5305b00bf1084fb742249867ac00ab244c61c4e9/src/args.rs#L125

This list of characters would also be nice to have in the config file for those that use non-QWERTY layouts.

----
I see there's another TODO item in the code about supporting more than 26 windows, which is something that may be run into more once multi-monitor support is is implemented. 

`wmfocus` handles that by starting to use multiple characters instead of one.

But honestly, I have three monitors and I doubt I ever have more than 26 visible windows, so limiting the tool to the 26 first visible windows also works for me!

But then, there's also the question of whether you also want to support focusing parent containers or just windows. Supporting just windows should handle more than 95% of  uses and could be another nice simplification. Supporting only windows will also help keep the number below 26.

**Comment by markstos** [comment]
I looked at this some today and believe I ran into an issue related this comment about a "kinda hacky" solution:
https://github.com/edzdez/sway-easyfocus/blob/main/src/ui.rs#L28

The way I understand the current code, the Sway windows are iterated over in a fixed order and the Easy Focus window labels are also assigned in a fixed order: Starting with "a" and extending through the alphabet.

To find which window to focus, it's assumed that the letter of the alphabets corresponds to the order of the Sway window nodes, so the letter can be used as an index of sorts. That assumption would break if random letter orders is allowed. 

---
Looking deeper, it appears that one "GTK window" is used per-output currently, so there is only listener per keyboard events per output currently. 

A proposed solution is to render one GTK overlay window per Sway "window node". I believe this would enable defining unique keyboard listener per GTK window. These listeners could defined using a closure where Sway's "window node id" can be captured and used to call the function to focus the window.

If I've understanding things correctly, this would solve the problem if the letters pressed being bound to the order of the windows. Also, it would support more than one letter per window-- setting the foundation of supporting more than 26 windows as well.

**Comment by edzdez** [comment]
Your understanding of the current code is indeed correct. Additionally, our solution seems like it may work, but I'm not sure if it's possible for multiple Gtk windows to listen for keypresses simultaneously (rather than only the one focused GtkWindow, as it is right now).

Unfortunately, I'm a bit busy this week so I don't think I'll be able to make progress on this immediately, but if you're interested, I'm open to PRs!

**Comment by markstos** [comment]
According to Google Bard, there are a couple options to register a single global keyboard event handler, which could then contain a dispatch table which maps specific keypresses to corresponding window IDs.

**Comment by markstos** [comment]
Fixed by #16

**Comment by edzdez** [comment]
Thank you for fixing this!
