### ISSUE TITLE
floating windows aren't given a label

### ISSUE THREAD

**Issue by edzdez** [edzdez/sway-easyfocus#3]
![image](https://github.com/edzdez/sway-easyfocus/assets/31393290/7886f7e0-cb58-496e-ac3a-aca6fa4da5b1)

**Comment by edzdez** [comment]
Sway seems to draw floating nodes above everything else -- after adding a check for floating windows, it seems like the label is drawn underneath them, and thus not visible through nontransparent windows.

As such, I'm closing this issue.

**Comment by matejdro** [comment]
As a workaround, could the label be drawn above/next to the floating window?
